### ISSUE TITLE
Show true damage dealt when having multiple arrows attacked

### ISSUE THREAD

**Issue by LeftCrosz** [Insprill/damage-indicator#10]
I would like to request a feature which is show stacked damage when having multiple arrows (projectile) attacked to enemy.

The picture below shows the bow can shoots multiple arrows at once. The bow's arrow base damage is 100
![image](https://user-images.githubusercontent.com/40970486/195589266-0c5b0aa6-ed2f-46bf-8074-f9eda23ab3fe.png)

The picture below shows the enemy supposed to take more than 500+ damage instead of 100 base damage because 5 arrows attacked the entity.
![image](https://user-images.githubusercontent.com/40970486/195589196-f1adabf9-5cec-48c7-9fbe-9e003e77679b.png)

**Comment by LeftCrosz** [comment]
The damage indicator somehow didn't accumulate but it sometimes only show 1 damage indicator instead. I sent you the link for the plugin for you to try it out.
Command: /ench spread
https://www.spigotmc.org/resources/zenchantments.12948/

**Comment by Insprill** [comment]
Why did you close this?

**Comment by LeftCrosz** [comment]
I was thinking about a different suggestion for it.
