### ISSUE TITLE
[Suggestion] Randomize indicator location

### ISSUE THREAD

**Issue by LeftCrosz** [Insprill/damage-indicator#11]
Add option to randomize the indicator's hologram location. When opponent having multiple projectile/hits in the same time then it would not be too messy or hard to see.
![image](https://user-images.githubusercontent.com/40970486/197326049-d93c7f28-c011-46f0-a61a-30abee161a99.png)

**Comment by Insprill** [comment]
Added in dff4ac349fd54366165bcce40eb25afcc57a2597, released in v1.11.0.
