### ISSUE TITLE
[Feature Request] Config for disabling damage & health indicators for invisible entities

### ISSUE THREAD

**Issue by peber7** [Insprill/damage-indicator#18]
I use this plugin and a the following configuration options would be very useful.
1) Add a configuration to disable showing damage and heal indicators for invisible entities
2) Similar to invisible entities, also add a configuration for players that are sneaking
3) Add a configuration to allow the heal indicators show values less then 1 (for custom EntityRegainHealthEvent from other plugins)

**Comment by peber7** [comment]
Awesome! This is great! Any chance you can update the heal indicators from the EntityRegainHealthEvent to also use the new config properties as well?

**Comment by Insprill** [comment]
Ahh that's what I get for coding at 3am, they're supposed to be applied to heath indicators too. Will fix it tonight.
