### ISSUE TITLE
Indicators get stuck when restarting the server

### ISSUE THREAD

**Issue by ii109** [Insprill/damage-indicator#19]
![gagbbn](https://github.com/Insprill/damage-indicator/assets/155603736/bb398357-043d-41a5-a203-20014f90ba43)
![hahah](https://github.com/Insprill/damage-indicator/assets/155603736/a02612d5-f7eb-4009-a5c3-da588b6f3eb2)

**Comment by Insprill** [comment]
What are your DI and server versions? Is there a way to reproduce it?

**Comment by disqetow** [comment]
I have same issue with paper lastest 1.20.4 and DamageIndicator lastest, maybe it cause when player hit mob and server close.

**Comment by Insprill** [comment]
I need a version number, not just latest. The indicators aren't entities that are spawned on the server, so simply disconnecting and reconnecting will clear them all for that client. I may look into it this weekend, but it's hard to say if/when I can fix the issue without a reliable way to reproduce it.

**Comment by disqetow** [comment]
paper-1.20.4-382 and DamageIndicator 1.10.1, I sure rejoin server not fix this issue.
Btw I can use /minecraft:kill @e[distance=..3] to clear them, I think it create entity on server.

**Comment by disqetow** [comment]
Confirm it cause when server close.

**Comment by disqetow** [comment]
I can confirm it cause when server close.

can reproduce it, pls see this viedo:
https://youtu.be/jbHp-eburBs

**Comment by Insprill** [comment]
Thank you for the video. I'll look into it this weekend.

**Comment by Insprill** [comment]
1.10.2 is now out to fix this issue. Thank you for the report!
