### ISSUE TITLE
Damage Indicator not work.

### ISSUE THREAD

**Issue by svdermant** [Insprill/Damage-Indicator#5]
Hello guy nice to meet you today i buy the damage indicator plugin and after my server starts and i'm not loggin in i get this error: https://pastebin.com/HW82KgLF - using the latest version: DamageIndicator version 1.3.2 and Server Version is : PaperMC 1.19 - so whats wrong with it? need you the full serverlog i can paste it to..

Here are the full serverlog:
https://pastebin.com/97fUG2LQ

How can i fix this or what is the called problem?

**Comment by Insprill** [comment]
Can you try updating your Paper build? I just started a 1.19 server on the latest version of Paper and it works fine.

**Comment by svdermant** [comment]
I can try it hopes it works i can do it tomorroe

**Comment by svdermant** [comment]
Hmm this is the only error message that i get [12:51:15 ERROR]: [DamageIndicator] Failed to load config file "locale/en-us.yml" as it has syntax errors! Use this website to find them: "https://www.yamlchecker.com/". ...  
its an typo in this file but i dont know where

**Comment by svdermant** [comment]
I check this file with the given content the page says its a valid yml but my log puts this error on start:
![damage](https://user-images.githubusercontent.com/50948584/184120026-8f2ae88a-fc3b-477b-b06f-d33e76707659.PNG)

There are my Versions:

![version](https://user-images.githubusercontent.com/50948584/184120248-68b2134f-e762-480f-9569-7b0adca30f9b.PNG)

**Comment by Insprill** [comment]
I'll look into that. You can ignore it for now. Is the original issue fixed though?
