### ISSUE TITLE
[Suggestion] Damage Indicators for MMOcore/MMOitems/Mythiclib

### ISSUE THREAD

**Issue by xuandattnvn1995** [Insprill/Damage-Indicator#7]
Add crit/magic damage display function. i would like you can add some indicators of it.
https://www.spigotmc.org/resources/mythiclib.90306/
https://www.spigotmc.org/resources/mmocore.70575/
https://www.spigotmc.org/resources/mmoitems-premium.39267/

**Comment by Insprill** [comment]
Duplicate of #6
